'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';import Link from 'next/link';
import {createOvertime,approveOvertime} from '../staff/operations-actions';
export default function OvertimeView({rows,contracts,canCreate,canApprove}:{rows:any[];contracts:any[];canCreate:boolean;canApprove:boolean}){
 const router=useRouter();const [contract,setContract]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await fn();setMessage('Đã lưu');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Không lưu được');}finally{setBusy(false);}}
 return <main className="space-y-5"><Link href="/dashboard/schedules/staff" className="text-sm underline">Lịch nhân sự</Link><h1 className="text-2xl font-semibold">Khai báo & duyệt OT</h1><p role="status" className="text-sm">{message}</p>
 {canCreate&&<form className="border rounded-lg p-4 space-y-4" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void act(async()=>{await createOvertime({starts_at:String(f.get('start'))+':00+07:00',ends_at:String(f.get('end'))+':00+07:00',reason:f.get('reason'),contract_id:contract||null,event_id:f.get('event')||null});form.reset();setContract('');});}}>
 <div className="grid sm:grid-cols-2 gap-4"><label className="text-sm">Bắt đầu (giờ Việt Nam)<input name="start" type="datetime-local" required className="block w-full border rounded p-2"/></label><label className="text-sm">Kết thúc (giờ Việt Nam)<input name="end" type="datetime-local" required className="block w-full border rounded p-2"/></label>
 <label className="text-sm">Hợp đồng<select className="block w-full border rounded p-2" value={contract} onChange={e=>setContract(e.target.value)}><option value="">Công việc nội bộ</option>{contracts.map(c=><option key={c.id} value={c.id}>{c.code}</option>)}</select></label>
 <label className="text-sm">Sự kiện<select key={contract} name="event" className="block w-full border rounded p-2"><option value="">Không chọn</option>{contracts.find(c=>c.id===contract)?.events.map((e:any)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div>
 <label className="block text-sm">Nội dung làm thêm<textarea required name="reason" className="block w-full border rounded p-2"/></label><button disabled={busy} className="bg-emerald-700 text-white px-4 py-2 rounded disabled:opacity-50">Gửi duyệt</button></form>}
 <div className="space-y-2">{rows.length===0&&<p>Chưa có yêu cầu OT.</p>}{rows.map(r=><article key={r.id} className="border rounded-lg p-4 text-sm space-y-2"><div className="flex flex-wrap justify-between gap-2"><strong>{r.user?.full_name}</strong><span>{({PENDING:'Chờ duyệt',APPROVED:'Đã duyệt',REJECTED:'Từ chối'} as any)[r.status]}</span></div><p>{new Date(r.starts_at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})} – {new Date(r.ends_at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</p><p>{r.contract?.contract_code||'Nội bộ'} · {r.reason}</p>{r.amount!=null&&<p>Tiền OT: {Number(r.amount).toLocaleString('vi-VN')} ₫</p>}{canApprove&&r.status==='PENDING'&&<div className="flex gap-3"><button disabled={busy} onClick={()=>act(()=>approveOvertime(r.id,'APPROVED'))} className="text-emerald-700 underline">Duyệt</button><button disabled={busy} onClick={()=>act(()=>approveOvertime(r.id,'REJECTED'))} className="underline">Từ chối</button></div>}</article>)}</div></main>;
}
