const fs = require('fs');

const rule = `
# AGENTS.md – Rules for High‑Quality Campaign Generation

> **[!IMPORTANT]** Ensure **double‑length content** for every generated Campaign deliverable while keeping the language natural, authentic, and grounded in realistic marketing voice.

- **Scope**: Applies to the \`ideas\` module (\`src/app/dashboard/marketing/ideas\`).
- **Requirement**: For each field within \`deliverables\` (\`customer_insight\`, \`main_message\`, \`tone_voice\`, \`hook_suggestion\`, \`caption\`, \`hashtags\`, \`script_details\`, \`seeding_comments\`) the generated text must be **at least twice** the token count of the baseline version (baseline being the default content generated by earlier pipelines).
- **Implementation Hint**: When constructing the JSON for a Campaign, duplicate the baseline descriptive content and enrich it with additional details, examples, and narrative depth **without forcing exaggerated drama**. Use techniques such as:
  - Expanding insights with **multiple persona scenarios** that reflect real customer motivations.
  - Adding **sub‑points** in main messages to deepen the argument.
  - Providing **expanded tone‑voice descriptions** that stay true to the brand’s authentic voice.
  - Extending hooks with **multi‑scene setups** that feel plausible and relatable.
  - Lengthening captions with **story arcs** and **call‑to‑action variations** that are logical and persuasive.
  - Including **extra hashtags** and **expanded seeding comment arrays** that reflect genuine audience reactions.
  - Enriching \`script_details\` with **additional camera angles, acting cues, and dialogues** (minimum 6 scenes per video) while keeping dialogue natural and credible.
- **Goal Flexibility**: The system must allow a *single* \`/goal\` request to generate **up to 10 Campaigns** while still respecting the double‑length rule for each deliverable.
- **Enforcement**: Any pipeline that inserts Campaign data into the \`marketing_contents\` table must validate the content length (e.g., by counting words) before insertion; if the content falls short, abort with an error and log a warning.
- **Future‑proof**: This rule persists across sessions; agents will automatically honor it without additional prompts.

---

*This rule ensures future \`/goal\` executions produce richly detailed, double‑length Campaigns with a natural, realistic tone, satisfying the user’s quality expectations.*
`;

fs.appendFileSync('.agents/AGENTS.md', rule, 'utf8');
console.log('Appended rule to .agents/AGENTS.md');
