'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';
import {saveVideoReport,savePerformanceVersion} from './actions';import {saveVideoRewardRule,approveVideoReward} from './reward-actions';
const metrics=[['views','Lượt xem'],['reach','Tiếp cận'],['likes','Thích'],['comments','Bình luận'],['shares','Chia sẻ'],['leads_generated','Khách tiềm năng'],['cost_spent','Chi phí']] as const;
export default function VideoReportsView({rows,users,canCreate,canUpdate}:{rows:any[];users:any[];canCreate:boolean;canUpdate:boolean}){
 const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [search,setSearch]=useState('');
 async function act(fn:()=>Promise<any>){if(busy)return;setBusy(true);setMessage('');try{const r=await fn();if(r?.success===false)throw new Error(r.error);setMessage('Đã lưu');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Không lưu được');}finally{setBusy(false);}}
 return <main className="space-y-5"><h1 className="text-2xl font-semibold">Báo cáo hiệu quả video</h1><p className="text-sm text-slate-600">Theo dõi các lần ghi nhận lượt xem, tương tác và khách tiềm năng của nội dung đã đăng.</p><p role="status" className="text-sm">{message}</p>
 {canCreate&&<details className="border p-4 rounded-lg"><summary className="cursor-pointer">Thêm video</summary><form className="space-y-3 mt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>saveVideoReport(true,{title:f.get('title'),actual_publish_date:f.get('date'),asset_link:f.get('url')}));}}><input aria-label="Tên video" name="title" required placeholder="Tên video" className="w-full border rounded p-2"/><div className="flex flex-wrap gap-3"><input aria-label="Ngày đăng" name="date" required type="date" className="border rounded p-2"/><input aria-label="Link video" name="url" required type="url" placeholder="Link video" className="border rounded p-2 flex-1"/></div><button disabled={busy} className="px-4 py-2 bg-emerald-700 text-white rounded">Lưu video</button></form></details>}
 {canUpdate&&<details className="border p-4 rounded-lg"><summary className="cursor-pointer">Cấu hình thưởng video</summary><form className="flex flex-wrap items-end gap-3 mt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>saveVideoRewardRule(Number(f.get('views')),Number(f.get('engagement'))));}}><label className="text-sm">₫ / 1.000 lượt xem<input name="views" required type="number" min="0" step="1" className="block border rounded p-2"/></label><label className="text-sm">₫ / tương tác (thích + bình luận + chia sẻ)<input name="engagement" required type="number" min="0" step="1" className="block border rounded p-2"/></label><button disabled={busy} className="border rounded px-4 py-2">Lưu mức thưởng</button></form><p className="text-sm mt-2 text-slate-600">Thưởng = số lượt xem / 1.000 × đơn giá + số tương tác × đơn giá. Mỗi video được duyệt thưởng một lần.</p></details>}
 <input aria-label="Tìm video" placeholder="Tìm tên video" value={search} onChange={e=>setSearch(e.target.value)} className="w-full border p-2 rounded"/>
 {rows.filter(r=>r.title?.toLowerCase().includes(search.toLowerCase())).map(r=><details key={r.id} className="border rounded-lg p-4"><summary className="cursor-pointer"><strong>{r.title}</strong><span className="ml-3 text-sm text-slate-500">{r.versions_count} lần ghi nhận · {(r.latest_log?.views||0).toLocaleString('vi-VN')} lượt xem</span></summary><div className="mt-4 space-y-4">
 {r.asset_link&&/^https?:\/\//i.test(r.asset_link)&&<a href={r.asset_link} target="_blank" rel="noreferrer" className="text-sm underline">Mở video</a>}
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Phiên bản</th>{metrics.map(([key,label])=><th className="p-2 text-right whitespace-nowrap" key={key}>{label}</th>)}</tr></thead><tbody>{r.performance_logs?.map((log:any)=><tr className="border-t" key={log.id}><td className="p-2">{log.version_name}<div className="text-xs text-slate-500">{new Date(log.logged_at).toLocaleDateString('vi-VN')}</div></td>{metrics.map(([key])=><td key={key} className="p-2 text-right">{Number(log[key]||0).toLocaleString('vi-VN')}</td>)}</tr>)}</tbody></table></div>
 {canCreate&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const input:any={version_name:f.get('version'),logged_at:new Date().toISOString()};for(const [key] of metrics)input[key]=Number(f.get(key));void act(()=>savePerformanceVersion(r.id,true,input));}}><input name="version" required aria-label="Tên lần ghi nhận" placeholder="Tên lần ghi nhận (VD: sau 7 ngày)" className="border rounded p-2 w-full"/><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{metrics.map(([key,label])=><label className="text-sm" key={key}>{label}<input name={key} type="number" min="0" required defaultValue="0" className="w-full block border rounded p-2"/></label>)}</div><button disabled={busy} className="px-4 py-2 bg-emerald-700 text-white rounded">Ghi nhận hiệu quả</button></form>}
 {canUpdate&&r.latest_log&&<form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>approveVideoReward(r.id,r.latest_log.id,String(f.get('user'))));}}><select name="user" required aria-label="Nhân viên nhận thưởng" className="border rounded p-2"><option value="">Nhân viên nhận thưởng</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select><button disabled={busy} className="border rounded px-4 py-2">Duyệt thưởng từ lần ghi nhận mới nhất</button></form>}
 </div></details>)}{rows.length===0&&<p>Chưa có video được ghi nhận.</p>}</main>;
}
