'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';import {savePayrollProfile,saveCommissionAllocation,finalizePayroll} from './actions';
import type {calculatePayroll} from '@/lib/payroll-calculation';
const fields=[['base_salary','Lương cơ bản'],['allowance','Phụ cấp'],['ot_hourly_rate','Đơn giá OT / giờ'],['late_per_minute','Khấu trừ / phút trễ'],['commission_percent','Hoa hồng (%)']] as const;
const money=(n:number)=>n.toLocaleString('vi-VN');
export default function PayrollView({period,result,profiles,contracts,canUpdate}:{period:string;result:{rows:ReturnType<typeof calculatePayroll>[];finalized:boolean};profiles:any[];contracts:any[];canUpdate:boolean}){
 const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [employee,setEmployee]=useState('');
 async function act(fn:()=>Promise<any>){if(busy)return;setBusy(true);setMessage('');try{await fn();setMessage('Đã lưu');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Không lưu được');}finally{setBusy(false);}}
 const profile=profiles.find(p=>p.user_id===employee);
 return <main className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">Bảng lương</h1><div className="flex flex-wrap gap-3"><input aria-label="Kỳ lương" type="month" value={period} onChange={e=>{if(e.target.value)router.push('/dashboard/payroll?period='+e.target.value);}} className="border rounded p-2"/><a href={'/dashboard/payroll/export?period='+period} className="border px-3 py-2 rounded text-sm">Xuất Excel</a></div></div>
 <p className="text-sm text-slate-600">{result.finalized?'Đã chốt kỳ lương':'Bảng tính tạm'} · Lương cơ bản + phụ cấp + OT đã duyệt + thưởng + hoa hồng − khấu trừ. Hoa hồng tính theo tháng ký hợp đồng và tỷ lệ phân bổ.</p><p role="status" className="text-sm">{message}</p>
 {canUpdate&&!result.finalized&&<details className="border p-4 rounded-lg"><summary className="cursor-pointer">Cấu hình lương nhân viên</summary><form className="space-y-3 mt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const p:any={user_id:employee};for(const [key] of fields)p[key]=key==='ot_hourly_rate'&&!f.get(key)?null:Number(f.get(key));void act(()=>savePayrollProfile(p));}}><select required aria-label="Nhân viên cấu hình lương" className="border rounded p-2" value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Chọn nhân viên</option>{result.rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><div key={employee} className="grid sm:grid-cols-3 gap-3">{fields.map(([key,label])=><label key={key} className="text-sm">{label}<input required={key!=='ot_hourly_rate'} name={key} type="number" min="0" step={key==='commission_percent'?'0.01':'1'} max={key==='commission_percent'?100:undefined} defaultValue={profile?.[key]??''} className="block w-full border rounded p-2"/></label>)}</div><button disabled={busy} className="bg-emerald-700 text-white rounded px-4 py-2">Lưu cấu hình</button></form></details>}
 {canUpdate&&!result.finalized&&<details className="border p-4 rounded-lg"><summary className="cursor-pointer">Phân bổ doanh số hợp đồng</summary><p className="text-sm mt-2 text-slate-600">Chọn đúng nhân viên nhận doanh số. Tổng tỷ lệ phân bổ mỗi hợp đồng không quá 100%.</p><form className="flex flex-wrap gap-3 mt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>saveCommissionAllocation(String(f.get('contract')),String(f.get('user')),Number(f.get('share'))));}}><select name="contract" aria-label="Hợp đồng" required className="border rounded p-2"><option value="">Hợp đồng</option>{contracts.map(c=><option key={c.id} value={c.id}>{c.contract_code}</option>)}</select><select name="user" aria-label="Nhân viên nhận doanh số" required className="border rounded p-2"><option value="">Nhân viên</option>{result.rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input aria-label="Tỷ lệ phân bổ" name="share" type="number" min="0.01" max="100" step="0.01" required placeholder="Tỷ lệ %" className="border rounded p-2 w-28"/><button disabled={busy} className="border rounded px-4 py-2">Lưu phân bổ</button></form></details>}
 <div className="overflow-x-auto border rounded-lg"><table className="w-full text-sm whitespace-nowrap"><thead className="bg-slate-50"><tr>{['Nhân viên','Cơ bản','Phụ cấp','OT','Thưởng','Hoa hồng','Khấu trừ','Thực nhận'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{result.rows.map(r=><tr key={r.id} className="border-t"><td className="p-3"><div>{r.name}</div><small>{r.code}{!r.configured&&' · Chưa cấu hình'}</small><details className="mt-1 whitespace-normal max-w-sm"><summary className="cursor-pointer text-emerald-700">Chi tiết</summary><p>{r.late} phút trễ</p>{r.details.map((d,i)=><p key={i} className="my-2">{d.source}: {money(d.amount)} ₫</p>)}</details></td>{[r.base,r.allowance,r.ot,r.bonus,r.commission,r.deductions,r.total].map((n,i)=><td key={i} className="p-3 text-right">{r.configured?money(n):'—'}</td>)}</tr>)}</tbody></table></div>
 <div className="flex flex-wrap justify-between gap-3"><strong>Tổng đã cấu hình: {money(result.rows.filter(r=>r.configured).reduce((s,r)=>s+r.total,0))} ₫</strong>{canUpdate&&!result.finalized&&<button disabled={busy||result.rows.some(r=>!r.configured)} onClick={()=>act(()=>finalizePayroll(period))} className="bg-emerald-700 text-white px-4 py-2 rounded disabled:opacity-50">Chốt bảng lương</button>}</div></main>;
}
