-- Canonical inventory code format:
--   size code:     FACTORY-SIZE          (J11111-50)
--   physical item: FACTORY-SIZE-ORDINAL  (J11111-50-001)
-- Existing SKU/QR values are intentionally preserved.

CREATE OR REPLACE FUNCTION public.normalize_inventory_code_part(value TEXT, fallback TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = public
AS $$
  SELECT COALESCE(NULLIF(regexp_replace(upper(trim(value)), '[^A-Z0-9]+', '', 'g'), ''), fallback)
$$;

CREATE OR REPLACE FUNCTION public.generate_garment_sku()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_factory TEXT;
  v_size TEXT;
  v_size_code TEXT;
  v_next_ordinal INTEGER;
BEGIN
  v_factory := public.normalize_inventory_code_part(NEW.factory_code::text, 'NOFACTORY');
  v_size := public.normalize_inventory_code_part(COALESCE(NEW.size_code::text, NEW.size::text), 'ONESIZE');
  v_size_code := concat_ws('-'::text, v_factory, v_size);

  -- Serialize allocation per factory/size, preventing duplicate QR codes when
  -- two intake requests run at the same time.
  PERFORM pg_advisory_xact_lock(hashtextextended(v_size_code, 0));

  SELECT COALESCE(MAX(substring(g.sku FROM '-([0-9]{3})$')::INTEGER), 0) + 1
  INTO v_next_ordinal
  FROM public.garments_inventory g
  WHERE g.sku LIKE v_size_code || '-%'
    AND g.sku ~ '-[0-9]{3}$';

  NEW.size_code := COALESCE(NULLIF(NEW.size_code::text, ''), NEW.size::text);
  NEW.size := COALESCE(NULLIF(NEW.size::text, ''), NEW.size_code::text);
  NEW.sku := concat_ws('-'::text, v_size_code, lpad(v_next_ordinal::text, 3, '0'));
  NEW.qr_code := NEW.sku;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_generate_garment_sku ON public.garments_inventory;
CREATE TRIGGER trigger_generate_garment_sku
BEFORE INSERT ON public.garments_inventory
FOR EACH ROW
EXECUTE FUNCTION public.generate_garment_sku();

CREATE OR REPLACE FUNCTION public.complete_inventory_declaration_impl(payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_model_id UUID;
  v_session_id UUID;
  v_line JSONB;
  v_qty INTEGER;
  v_total INTEGER := 0;
  v_base_sku TEXT;
BEGIN
  IF COALESCE(payload ->> 'name', '') = '' THEN RAISE EXCEPTION 'Tên sản phẩm là bắt buộc'; END IF;
  IF COALESCE(payload ->> 'location_floor', '') = '' THEN RAISE EXCEPTION 'Vị trí lầu/tầng là bắt buộc'; END IF;
  IF COALESCE(payload ->> 'factory_code', '') = '' THEN RAISE EXCEPTION 'Mã nhà sản xuất là bắt buộc'; END IF;

  FOR v_line IN
    SELECT value FROM jsonb_array_elements(COALESCE(payload -> 'size_lines', '[]'::jsonb)) AS size_rows(value)
  LOOP
    v_qty := COALESCE((v_line ->> 'quantity')::INTEGER, 0);
    IF COALESCE(v_line ->> 'size_code', '') = '' THEN RAISE EXCEPTION 'Size là bắt buộc'; END IF;
    v_total := v_total + GREATEST(v_qty, 0);
  END LOOP;
  IF v_total <= 0 THEN RAISE EXCEPTION 'Tổng số lượng phải lớn hơn 0'; END IF;

  -- A model can contain several sizes, so its stable identity is the factory
  -- code. Size-specific and physical codes are generated by the trigger.
  v_base_sku := public.normalize_inventory_code_part(payload ->> 'factory_code', 'NOFACTORY');

  INSERT INTO public.garment_models (
    name, category, factory_code, base_sku, group_type, style_details,
    material_pattern, color_code, color_name, suit_product_type, button_style,
    pattern_code, image_url, tag_image_url, additional_images,
    default_location_floor, default_location_shelf, default_location_tier,
    fit_note, size_system, supplier
  ) VALUES (
    payload ->> 'name', payload ->> 'category', NULLIF(payload ->> 'factory_code', ''), v_base_sku,
    payload ->> 'group_type', payload ->> 'style_details', payload ->> 'material_pattern',
    payload ->> 'color_code', payload ->> 'color_name', payload ->> 'suit_product_type',
    payload ->> 'button_style', payload ->> 'pattern_code', payload ->> 'image_url',
    payload ->> 'tag_image_url', COALESCE(payload -> 'additional_images', '[]'::jsonb),
    payload ->> 'location_floor', payload ->> 'location_shelf', payload ->> 'location_tier',
    payload ->> 'fit_note', payload ->> 'size_system', NULLIF(payload ->> 'supplier', '')
  )
  ON CONFLICT (base_sku) DO UPDATE SET
    name = EXCLUDED.name,
    factory_code = COALESCE(EXCLUDED.factory_code, garment_models.factory_code),
    group_type = EXCLUDED.group_type,
    style_details = EXCLUDED.style_details,
    material_pattern = EXCLUDED.material_pattern,
    color_code = EXCLUDED.color_code,
    color_name = EXCLUDED.color_name,
    suit_product_type = EXCLUDED.suit_product_type,
    button_style = EXCLUDED.button_style,
    pattern_code = EXCLUDED.pattern_code,
    image_url = COALESCE(EXCLUDED.image_url, garment_models.image_url),
    tag_image_url = COALESCE(EXCLUDED.tag_image_url, garment_models.tag_image_url),
    additional_images = EXCLUDED.additional_images,
    default_location_floor = EXCLUDED.default_location_floor,
    default_location_shelf = EXCLUDED.default_location_shelf,
    default_location_tier = EXCLUDED.default_location_tier,
    fit_note = EXCLUDED.fit_note,
    size_system = EXCLUDED.size_system,
    supplier = COALESCE(EXCLUDED.supplier, garment_models.supplier),
    updated_at = NOW()
  RETURNING id INTO v_model_id;

  INSERT INTO public.inventory_intake_sessions (
    intake_type, model_id, location_floor, location_shelf, location_tier,
    supplier, notes, total_quantity, created_by
  ) VALUES (
    COALESCE(payload ->> 'intake_type', 'INITIAL_AUDIT'), v_model_id,
    payload ->> 'location_floor', payload ->> 'location_shelf', payload ->> 'location_tier',
    NULLIF(payload ->> 'supplier', ''), NULLIF(payload ->> 'notes', ''), v_total, auth.uid()
  ) RETURNING id INTO v_session_id;

  FOR v_line IN
    SELECT value FROM jsonb_array_elements(payload -> 'size_lines') AS size_rows(value)
  LOOP
    v_qty := COALESCE((v_line ->> 'quantity')::INTEGER, 0);
    IF v_qty <= 0 THEN CONTINUE; END IF;

    INSERT INTO public.inventory_intake_lines (
      session_id, model_id, size_system, size_code, quantity,
      height_note, weight_note, fit_note, purchase_price
    ) VALUES (
      v_session_id, v_model_id, COALESCE(v_line ->> 'size_system', payload ->> 'size_system', 'VN'),
      v_line ->> 'size_code', v_qty, v_line ->> 'height_note', v_line ->> 'weight_note',
      v_line ->> 'fit_note', COALESCE((v_line ->> 'purchase_price')::NUMERIC, 0)
    );

    FOR i IN 1..v_qty LOOP
      INSERT INTO public.garments_inventory (
        model_id, intake_session_id, name, category, factory_code, group_type,
        style_details, material_pattern, size, size_code, size_system, color,
        color_code, suit_product_type, button_style, pattern_code, image_url,
        tag_image_url, additional_images, location_floor, location_shelf,
        location_tier, status, purchase_price, purchase_date, height_note,
        weight_note, fit_note, supplier
      ) VALUES (
        v_model_id, v_session_id, payload ->> 'name', payload ->> 'category', payload ->> 'factory_code',
        payload ->> 'group_type', payload ->> 'style_details', payload ->> 'material_pattern',
        v_line ->> 'size_code', v_line ->> 'size_code',
        COALESCE(v_line ->> 'size_system', payload ->> 'size_system', 'VN'),
        payload ->> 'color_name', payload ->> 'color_code', payload ->> 'suit_product_type',
        payload ->> 'button_style', payload ->> 'pattern_code', payload ->> 'image_url',
        payload ->> 'tag_image_url', COALESCE(payload -> 'additional_images', '[]'::jsonb),
        payload ->> 'location_floor', payload ->> 'location_shelf', payload ->> 'location_tier',
        'AVAILABLE', COALESCE((v_line ->> 'purchase_price')::NUMERIC, 0), CURRENT_DATE,
        v_line ->> 'height_note', v_line ->> 'weight_note', v_line ->> 'fit_note',
        NULLIF(payload ->> 'supplier', '')
      );
    END LOOP;
  END LOOP;

  RETURN jsonb_build_object(
    'model_id', v_model_id,
    'session_id', v_session_id,
    'total_quantity', v_total,
    'base_sku', v_base_sku
  );
END;
$$;

REVOKE ALL ON FUNCTION public.complete_inventory_declaration_impl(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.complete_inventory_declaration_impl(JSONB) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.complete_inventory_declaration(JSONB) TO authenticated;
